### ISSUE TITLE
Remove non-pooled driver.

### ISSUE THREAD

**Issue by yoroto** [awslabs/amazon-qldb-driver-dotnet#19]
The initial goal of having non-pooled driver was to allow the users to use a custom connection pooling library. But having a non-pooled driver has presented couple of  problems , in terms of  customer experience:

1. Customers get confused while choosing the pooled or non-pooled implementation, especially when we don’t have a clear documentation addressing this specifically and we recommend using pooled driver.

2. There is nothing that the non-pooled driver can do better than pooled driver and there exists no reason from a customer’s perspective to use a non-pooled driver version. The need to use a connection pooling library while we offer pooled driver seems redundant.

**Comment by othonrsanchez** [comment]
Resolving as issue was fixed with the PR https://github.com/awslabs/amazon-qldb-driver-dotnet/pull/20
