### ISSUE TITLE
Question about public release of the .NET driver

### ISSUE THREAD

**Issue by stage88** [awslabs/amazon-qldb-driver-dotnet#21]
First of all, many thanks to the contributors of the .NET driver for QLDB, your work is very much appreciated.

Are there any plans to release this driver as RC or public release? We are in early stages of evaluating this package and look forward to having a stable .NET SDK.

**Comment by othonrsanchez** [comment]
Hi stage88,

Thanks for your interest on the .net driver. We are still working on the driver and we are looking to release it in a short term.

We'll keep you posted when it happens.

**Comment by stage88** [comment]
@othonrsanchez Thanks!

**Comment by stage88** [comment]
Hi @othonrsanchez, thats great news, many thanks to your team for the hard work. I'll spend some time next week to upgrade our code base.

**Comment by othonrsanchez** [comment]
You are welcome! I'll keep the issue open to update you once we realize it.
