### ISSUE TITLE
Avoid blocking on asynchronous code and use async all the way

### ISSUE THREAD

**Issue by adrianiftode** [awslabs/amazon-qldb-driver-dotnet#28]
The Session class block on asynchronous code. This is ineffective for high demand web apps.

The symptom of this is the usage of calls like `GetAwaiter().GetResult()`. This blocks the calling thread until the response is received. The optimal behavior is to free the calling thread to handle other requests and once a response comes in any thread can continue the initial execution.

So instead of
```csharp
private SendCommandResponse SendCommand(SendCommandRequest request)
        {
            request.SessionToken = this.sessionToken;
            this.logger.LogDebug("Sending request: {}", request);
            return this.SessionClient.SendCommandAsync(request).GetAwaiter().GetResult();
        }
``` 
There should be something like

```csharp
 private async Task<SendCommandResponse> SendCommand(SendCommandRequest request)
        {
            request.SessionToken = this.sessionToken;
            this.logger.LogDebug("Sending request: {}", request);
            return await this.SessionClient.SendCommandAsync(request);
        }
```

This change will propagate through the code base, so for example, `StartTransaction` also should not block, so on.

**Comment by yoroto** [comment]
Hi @adrianiftode 

Thank you for submitting the ticket and the PR! We will discuss and get back to you asap.

**Comment by adrianiftode** [comment]
Hey @yoroto. Did you guys get the time to check this? I integrated this library with another open-source project used by people to create audit logs, so it really needs to be highly performant. Let me know at least your plans.

**Comment by simonz-bq** [comment]
Hi @adrianiftode,

Sorry for the delayed response! We were taking time to decide how to properly incorporate async support whilst keeping existing workflows functional. The upcoming release is going to add support for asynchronous workflows.
