### ISSUE TITLE
IonTextWriterBuilder write timestamp fails

### ISSUE THREAD

**Issue by jairveder** [awslabs/amazon-qldb-driver-dotnet#52]
When using the IonTextWriterBuilder with IonTextOptions { TimestampAsMillis = false } writing of timestamps result in an System.FormatException.

Example code
```
{
      using (var tw = new StringWriter())
      using (var writer = IonTextWriterBuilder.Build(tw, new IonTextOptions { TimestampAsMillis = false }))
      {
          writer.Flush();
          writer.StepIn(IonType.Struct);

          writer.SetFieldName("exampleDate");
          writer.WriteTimestamp(new Timestamp(exampleDate));

          writer.StepOut();
          writer.Finish();
      
          command = tw.ToString();
      }
      
      var result = IonLoader.Default.Load(command);
}
```

Executing this results in the following exception: 
![image](https://user-images.githubusercontent.com/37770531/105819385-68b14000-5fb8-11eb-9cd6-a04f1ab1552c.png)

Package version: 1.0.1

**Comment by simonz-bq** [comment]
Moved to https://github.com/amzn/ion-dotnet/issues/132
